# Generated by Django 5.0.7 on 2024-07-24 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_heading', models.CharField(max_length=200)),
                ('blog_text', models.CharField(max_length=20000)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
