# Generated by Django 5.0.7 on 2024-07-24 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_blogpost_blog_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='blog_text',
            field=models.TextField(default='Text', max_length=20000),
        ),
    ]
