# Generated by Django 5.0.7 on 2024-07-25 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpost_blog_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='description',
            field=models.CharField(default='Description', max_length=200),
        ),
    ]
